apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
spec:
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
      - name: authentication-service
        image: "tsawler/authentication-service:1.0.0"
        env:
          - name: DSN
            value: "host=host.minikube.internal port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  selector:
    name: authentication-service
  ports:
  - port: 80
    targetPort: 80
    name: main-port
    protocol: TCP
