apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-service
spec:
  selector:
    matchLabels:
      app: logger-service
  template:
    metadata:
      labels:
        app: logger-service
    spec:
      containers:
      - name: logger-service
        image: tsawler/logger-service:1.0.1
        ports:
        - containerPort: 80    #web port
        - containerPort: 5001  #rpc port
        - containerPort: 50001 #grpc port

---
apiVersion: v1
kind: Service
metadata:
  name: logger-service
spec:
  selector:
    app: logger-service
  ports:
  - port: 5001
    targetPort: 5001
    name: rpc-port
    protocol: TCP
  - port: 50001
    targetPort: 50001
    name: grpc-port
    protocol: TCP
  - port: 80
    targetPort: 80
    name: web-port
    protocol: TCP
