apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer-service
spec:
  selector:
    matchLabels:
      app: mailer-service
  template:
    metadata:
      labels:
        app: mailer-service
    spec:
      containers:
      - name: mailer-service
        image: tsawler/mail-service:1.0.0
        env:
          - name: MAIL_DOMAIN
            value: ""
          - name: MAIL_HOST
            value: "localhost"
          - name: MAIL_PORT
            value: "1025"
          - name: MAIL_ENCRYPTION
            value: "none"
          - name: MAIL_USERNAME
            value: ""
          - name: MAIL_PASSWORD
            value: ""
          - name: FROM_NAME
            value: "John Smith"
          - name: FROM_ADDRESS
            value: "admin@eaxmple.com"
        ports:
          - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: mailer-service
spec:
  selector:
    app: mailer-service
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: main-port

